### PR TITLE
Improve PHP 8.1 compatibility

### PR DESCRIPTION
**Pull request by sadikoff**
Hey,

using a package with php8.1 got a lot of deprecated messages
> Implicit conversion from float <float_number> to int loses precision

also to work with PHP 8.1 was necessary to reconfigure the test system, and drop PHP 5.3-5.6 so it sounds like a BC so we will need to publish a new major version to not brake existing projects which uses this package =)

### CODE REVIEW

**Comment by sadikoff** [comment]
Hello @delphiki I hope you are doing well and find some time to review it =)

Cheers!

**Comment by delphiki** [comment]
Hello @sadikoff, thanks for the PR! :)

Sorry I haven't been very responsive lately on PRs & issues submitted.
I'll try my best to review yours properly by tomorrow!

**Review by weaverryan — APPROVED** [review]
Looks minor, but solid 👍

**Comment by delphiki** [comment]
A few months late, sorry, but this looks good to me! Thanks @sadikoff 

And thanks @weaverryan for the review (and reminder)!

**Pull request merged**
