### PR TITLE
Handle more than 2 digits long hours

### PR DESCRIPTION
**Pull request by dzsubek**
Issue #47 https://www.w3.org/TR/webvtt1/#webvtt-timestamp

### CODE REVIEW

**Comment by dzsubek** [comment]
Travis does not support PHP 5.3 on Trusty
https://docs.travis-ci.com/user/reference/trusty#PHP-images
https://github.com/travis-ci/travis-ci/issues/7693

**Comment by delphiki** [comment]
@dzsubek Looks great, thanks for the PR!

Could you please remove PHP 5.3 from the travis config file? (even if the library is supposed to support PHP 5.3, it will disappear eventually).

**Comment by dzsubek** [comment]
Done. Thanks.

**Comment by delphiki** [comment]
Thank you!

**Pull request merged**
