### PR TITLE
Add possibility to change styles version for SubstationalphaFile

### PR DESCRIPTION
**Pull request by danut007ro**
Hello,

I added the possibility to change styles version. It defaults to your value v4+ (advanced substationalpha), but not it can be changed to v4 (substationalpha).

Thanks!

### CODE REVIEW

**Comment by danut007ro** [comment]
Any news on merging this?

**Comment by delphiki** [comment]
Sorry, I kinda forgot your PR.
Now that I started to work on this project again, I'll have a look at it by the end of the week :)

**Comment by danut007ro** [comment]
Great! Thanks, and the other one too.

**Comment by delphiki** [comment]
Yep :)

**Comment by delphiki** [comment]
I made some slight modifications, but thanks again!

I'll have a look into the other one now.

**Pull request merged**
