### PR TITLE
Update PHP line Breaks

### PR DESCRIPTION
**Pull request by eliasnicolas07**
(Minor change PHP Line Breaks, because it's the same, you could delete all)

### CODE REVIEW

**Comment by delphiki** [comment]
I'm not sure this line break should be added, as the PHP_EOL value depends on the server's config.

The line breaks are very specific and have to be specified explicitly for certain subtitles formats, so replacing them with PHP_EOL does not seem relevant.

**Comment by eliasnicolas07** [comment]
That's the point. You use `const UNIX_LINE_ENDING    = "\n";` Instead of using the one that the server uses. Each case is limited to a single Line break. If your server runs "Windows", is transforming it all to "\n" When you set `$this->lineEnding = self::UNIX_LINE_ENDING` Even if you don't need it. Here I didn't do all the work. But from this, i added new formats, change a few things despite this line ending thing, (which I change it all) (If you want, you can review it)
I give you an example:
If you have an SRT with line break "Windows Type" On "Mac server" and you change it to "UNIX" type. See the logic? Anyway, thank you answering.

**Comment by delphiki** [comment]
My point is that the line breaks are depending on the subtitles format, not on the platform.

For example, initially the webvtt spec specified that the only allowed line terminator was CRLF (even if it now accepts all types of line endings), so if it'd stayed that way, we would have had no choice but to specified the windows line ending explicitly.

My mistake might have been to name the constants on a "platform convention", where it should have been something like `CRLF_LINE_ENDING`, `CR_LINE_ENDING` and `LF_LINE_ENDING` instead.

But maybe I'm not seeing this through, and we need other opinions on the mater.
Ping @vkhramtsov, @danut007ro, @z38 ?

**Comment by vkhramtsov** [comment]
From my point of view we should use platform independent line endings, because usually we don't need to have result dependent on server platform.

**Pull request closed without merging**
